theme: jekyll-theme-cayman
title: "Visual-textual Dermatoglyphic Animal Biometrics: A First Case Study on Panthera tigris"
description: "Wenshuo Li, Majid Mirmehdi, Tilo Burghardt"
show_downloads: true
baseurl: "/vt-tiger-bio.github.io"
url: "https://wenshuoli001.github.io"
